exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: conda/meta.yaml

  # Can run individually with `pre-commit run black --all-files`
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  # Can run individually with `pre-commit run isort --all-files`
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile
          - black

  # Can run individually with `pre-commit run mypy --all-files`
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        language: system

  # - repo: local
  #   hooks:
  #    - id: pytest # pytest is a pre-commit hook
  #      name: pytest
  #      entry: pytest
  #      language: system
  #      types: [python]
  #      exclude: ^venv/ ^.git/ ^.vscode/ ^.DS_Store
