[project]
name = "pism-emulator"
maintainers = [{name = "Andy Aschwanden", email = "andy.aschwanden@gmail.com"}]
description = """PISM Emulator and MALA MCMC Sampler"""
readme = "README.md"
requires-python = ">3.9"
license = {text = "GPL 3.0"}
classifiers = [
        "License :: OSI Approved :: Apache Software License",
        "Natural Language :: English",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Postprocessing",
        ]
dynamic = ["dependencies", "version"]

[project.scripts]
train-emulator = "pism_emulator.emulators.speed.train:main"
evaluate-emulator = "pism_emulator.emulators.speed.evaluate:main"
sample-posterior-speed = "pism_emulator.mcmc.sample_speed:cli"
sample-posterior-pdd = "pism_emulator.mcmc.sample_pdd:cli"
sample-posterior-pdd-reparametrized = "pism_emulator.mcmc.sample_pdd_reparametrized:cli"
sample-posterior-pdd-verify = "pism_emulator.mcmc.sample_pdd_verify:cli"
sample-posterior-pdd-reparametrized-verify = "pism_emulator.mcmc.sample_pdd_reparametrized_verify:cli"
plot-posterior = "pism_emulator.mcmc.plot_posterior:cli"

[tool.setuptools.packages.find]
include = ["pism_emulator*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["pism_emulator"]


[tool.flake8]
# https://pep8.readthedocs.io/en/latest/intro.html#error-codes
ignore = """
    E203,
    E501,
    W503,
    W605,
    C901,
    F841,
    E722,
    E402,
    F722,
    """
# Max width of Github code review is 119 characters
max-line-length = 119
max-complexity = 18
exclude = [
    ".tox",
    ".git",
    "*/migrations/*",
    ".mypy_cache",
    ".pytest_cache",
    "*__init__.py",
    "venv"
    ]

[tool.isort]
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
line_length = 120

[tool.pycodestyle]
max-line-length = 120
exclude = [
    ".tox",
    ".git",
    "*/migrations/*",
    ".mypy_cache",
    ".pytest_cache",
    "*__init__.py",
    "venv"
    ]


[tool.mypy]
python_version = 3.11
check_untyped_defs = "True"
ignore_missing_imports = "True"
warn_unused_ignores = "True"
warn_redundant_casts = "True"
warn_unused_configs = "True"
namespace_packages = "True"
exclude = ["data"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
      \.eggs
    | \.git
    | \.mypy_cache
    | _build
    | conda
    | docs
 )/
'''

[tool.pylint."MASTER"]
jobs = 1
ignored-modules = [
    "torch",
    "torch.*",
    "lightning",
    "lightning.*",
    "arviz",
    "matplotlib",
    "matplotlib.*",
    "scipy.stats",
]

[tool.pylint.messages_control]
disable = """
    too-many-lines,
    no-else-return,
    bare-except
"""

[tool.pylint.format]
max-line-length = 120

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
    "GL08"
]
