version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Install pism-emulator
          command: |
            pip install -r requirements_tests.txt --user
            python setup.py install --user
      - run:
          name: Run tests
          command: |
            pytest -v -W ignore::UserWarning ./tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
